spring:
  r2dbc:
#    url: "r2dbc:postgresql://172.17.0.2:5432/postgres"
    url: "r2dbc:postgresql://172.17.0.2:5432/postgres?options=statement_timeout=1s"
    username: postgres
    password: postgres